version: '2'

services:
  db:
    image: postgres:15.6-alpine
    restart: always
    container_name: db
    environment:
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - my-network
  app:
    image: demo:latest
    build:
      dockerfile: Dockerfile
    container_name: app
    ports:
      - "8090:8090"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/${DATABASE_NAME}
      - SPRING_DATASOURCE_USERNAME=${DATABASE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DATABASE_PASSWORD}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create-drop
      - SPRING_JPA_SHOW_SQL=true
      - SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL=true
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.PostgreSQLDialect
      - JWT_SECRET=${SECRET_KEY}
    networks:
      - my-network
  frontend:
    ports:
      - "3000:3000"
    environment:
       - CHOKIDAR_USEPOLLING=true
    container_name: frontend
    build: ./frontend
    depends_on:
      - app
    volumes:
      - './:/frontend'
      - '/frontend/node_modules'
    stdin_open: true
    command: npm start
    networks:
      - my-network
volumes:
  db:
    driver: local
networks:
  my-network:
    driver: bridge